<?php

use Illuminate\Database\Seeder;
use App\Course;

class CoursesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $courses = [
            ['code' => 'SSBT with BRM','description' => 'Ship Simulator and Bridge Teamwork with BRM', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '5', 'added_by' => '1'],
            ['code' => 'STSM','description' => 'Ship Handling & Maneuvering in Critical Conditions (Advance SSBT)', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '5', 'added_by' => '1'],
            ['code' => 'ECDIS','description' => 'Electronic Chart Display Information System', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '5', 'added_by' => '1'],
            ['code' => 'AIS','description' => 'Automatic Identification System', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '2', 'added_by' => '1'],
            ['code' => 'BRM','description' => 'Bridge Resource Management', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '3', 'added_by' => '1'],
            ['code' => 'RFPNW','description' => 'Ratings Forming Part of Navigational Watch', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '5', 'added_by' => '1'],
            ['code' => 'BTM','description' => 'Bridge Team Management', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '3', 'added_by' => '1'],
            ['code' => 'MLCD-F1','description' => 'Function 1: Navigation at the Management Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '30', 'added_by' => '1'],
            ['code' => 'MLCDU-F1','description' => 'Function 1: Updating Navigation at the Management Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '7', 'added_by' => '1'],
            ['code' => 'MLCD-F2','description' => 'Function 2: Cargo Handling and Stowage at the Manage-ment Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '9', 'added_by' => '1'],
            ['code' => 'MLCD-F3','description' => 'Function 3: Controlling of the Ship and Care of Person on Board', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '14', 'added_by' => '1'],
            ['code' => 'MLCDU-F3','description' => 'Function 3: Updating Controlling of the Ship and Care of Person on Board', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '3', 'added_by' => '1'],
            ['code' => 'OICU-DF1A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-A', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '7', 'added_by' => '1'],
            ['code' => 'OICU-DF3A','description' => 'Updating Training for Officer In Charge of a Navigational Watch F3 Part-A', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '3', 'added_by' => '1'],
            ['code' => 'OICU-DF1B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F1 Part-B', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '12', 'added_by' => '1'],
            ['code' => 'OICU-DF2B','description' => 'Updating Training for Officer In Charge of a Navigational Watch F2 Part-B', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '4', 'added_by' => '1'],
            ['code' => 'OICU-DF3B','description' => 'Updating Training for Officer In Charge of Navigational Watch F3 Part-B', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '7', 'added_by' => '1'],
            ['code' => 'ERSC with ERRM','description' => 'Engine Room Simulator Courses with Engine Room Resource Management', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '5', 'added_by' => '1'],
            ['code' => 'ERRM','description' => 'Engine Room Resource Management', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '3', 'added_by' => '1'],
            ['code' => 'ETM','description' => 'Engine Team Management', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '3', 'added_by' => '1'],
            ['code' => 'RFPEW','description' => 'Ratings Forming Part of Engineering Watching', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '5', 'added_by' => '1'],
            ['code' => 'AUMA','description' => 'Auxiliary Machinery', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '5', 'added_by' => '1'],
            ['code' => 'COEN','description' => 'Control Engineering', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '5', 'added_by' => '1'],
            ['code' => 'MLCE-F1','description' => 'FUNCTION 1: Marine Engineering at the Management Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '21', 'added_by' => '1'],
            ['code' => 'MLCEU-F1','description' => 'FUNCTION 1: Updating Marine Engineering at the Management Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '10', 'added_by' => '1'],
            ['code' => 'MLCE-F2','description' => 'FUNCTION 2: Electrical, Electronic and Control Engineer-ing at the Management Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '24', 'added_by' => '1'],
            ['code' => 'MLCEU-F2','description' => 'FUNCTION 2: Updating Electrical, Electronic and Control Engineer-ing at the Management Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '17', 'added_by' => '1'],
            ['code' => 'MLCE-F3','description' => 'FUNCTION 3: Maintenance and Repair at the Manage-ment Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '8', 'added_by' => '1'],
            ['code' => 'MLCEU-F3','description' => 'FUNCTION 3: Updating Maintenance and Repair at the Manage-ment Level', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '4', 'added_by' => '1'],
            ['code' => 'MLCE-F4','description' => 'FUNCTION 4: Controlling the Operation of the Ship and Care of Person on Board', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '18', 'added_by' => '1'],
            ['code' => 'MLCEU-F4','description' => 'FUNCTION 4: Updating Controlling the Operation of the Ship and Care of Person on Board', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '3', 'added_by' => '1'],
            ['code' => 'OICU-EF1A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F1 Part-A', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '7', 'added_by' => '1'],
            ['code' => 'OICU-EF2A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F2 Part-A', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '2', 'added_by' => '1'],
            ['code' => 'OICU-EF4A','description' => 'Updating Training for Officer In Charge of an Engineering Watch F4 Part-A', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '3', 'added_by' => '1'],
            ['code' => 'OICU-EF1B','description' => 'Updating Training for Officer In Charge of Engineering Watch F1 Part-B', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '12', 'added_by' => '1'],
            ['code' => 'OICU-EF2B','description' => 'Updating Training for Officer In Charge of Engineering Watch F2 Part-B', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '8', 'added_by' => '1'],
            ['code' => 'OICU-EF4B','description' => 'Updating Training for Officer In Charge of Engineering Watch F4 Part-B', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '4', 'added_by' => '1'],
            ['code' => 'MAR-E','description' => 'Maritime English', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '5', 'added_by' => '1'],
            ['code' => 'ANTI-PIRACY','description' => 'Anti-Piracy', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '1', 'added_by' => '1'],
            ['code' => 'MARPOL 1 TO 6','description' => 'Marine Pollution and Prevention (73/78 Annexes 1 to 6)', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '5', 'added_by' => '1'],
            ['code' => 'MARLAW','description' => 'Maritime Law for Ship Officers (for OIC)', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '5', 'added_by' => '1'],
            ['code' => 'MECA','description' => 'Medical Care', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '5', 'added_by' => '1'],
            ['code' => 'MEFA','description' => 'Medical Emergency First Aid', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '4', 'added_by' => '1'],
            ['code' => 'SDSDSAT','description' => 'Seafarer’s with Designated Security Duties and Security Awareness Training', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '1', 'added_by' => '1'],
            ['code' => 'BT','description' => 'Basic Training', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '8', 'added_by' => '1'],
            ['code' => 'BTOC','description' => 'Basic Training for Oil and Chemical Tanker', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '6', 'added_by' => '1'],
            ['code' => 'BTLGT','description' => 'Basic Training in Liquefied Gas Tanker', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '6', 'added_by' => '1'],
            ['code' => 'PSCRB','description' => 'Proficiency in Survival Craft an Rescue Boats', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '4', 'added_by' => '1'],
            ['code' => 'PFRB','description' => 'Profiency in Fast Rescue Boat', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '4', 'added_by' => '1'],
            ['code' => 'ATF','description' => 'Advance Training in Fire Fighting', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '4', 'added_by' => '1'],
            ['code' => 'DW','description' => 'Deck Watchkeeping', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '5', 'added_by' => '1'],
            ['code' => 'DPAC','description' => 'SSBT Assessment', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '1', 'added_by' => '1'],
            ['code' => 'EW','description' => 'Engine Watchkeeping', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '5', 'added_by' => '1'],
            ['code' => 'EPAC','description' => 'ERSC Assessment', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'engine','duration' => '1', 'added_by' => '1'],
            ['code' => 'SSATSDSD','description' => 'Ship Security Awareness Training and Seafarers with Designated Security Duties', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '1', 'added_by' => '1'],
            ['code' => 'UTBS','description' => 'Updating Training for Basic Safety', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '1', 'added_by' => '1'],
            ['code' => 'RTBS','description' => 'Refresher Training for Basic Safety', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '2', 'added_by' => '1'],
            ['code' => 'FFLB','description' => 'Free Fall Life Boat', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '1', 'added_by' => '1'],
            ['code' => 'FFLBC','description' => 'Free Fall Lifeboat Course (Coxswain)', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '2', 'added_by' => '1'],
            ['code' => 'RATF','description' => 'Refresher Training on Advance Fire Fighting', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '2', 'added_by' => '1'],
            ['code' => 'RPSCRB','description' => 'Refresher Proficiency in Survival Craft & Rescue Boat', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '2', 'added_by' => '1'],
            ['code' => 'RPFRB','description' => 'Refresher Proficiency in Fast Rescue Boat', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '2', 'added_by' => '1'],
            ['code' => 'SSO','description' => 'Ship Security Officer Course', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '3', 'added_by' => '1'],
            ['code' => 'SD','description' => 'Smoke Diving', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '2', 'added_by' => '1'],
            ['code' => 'H2S','description' => 'Hydrogen Sulfide Awareness', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'common','duration' => '1', 'added_by' => '1'],
            ['code' => 'RNPUA','description' => 'Radar Navigation, Radar Plotting and Use of ARPA (ROPA)', 'accreditation_body' => 'marina','aims' => null, 'objectives_header' => null, 'objectives' => null, 'target_audience' => null, 'prerequisites' => null, 'validity' => null, 'category' => 'deck','duration' => '8', 'added_by' => '1'],
            ['code' => 'BOSIET','description' => 'Basic Offshore Safety Induction and Emergency Training', 'accreditation_body' => 'opito','aims' => 'The aim of the BOSIET is to introduce delegates to the specific safety issues and regimes relevant to offshore installations, and to equip them with the basic emergency response knowledge and skills for travelling to and from offshore installations by helicopter.', 'objectives_header' => 'The objectives of the BOSIET are that delegates will be able to:', 'objectives' => 'Identify the generic hazards which are specific to offshore oil and gas installations, potential risks associated with those hazards, and how controls are put in place to eliminate or reduce risks.\\n\\nIdentify key offshore related safety regulations and explain the basic safety management concepts\\n\\nDemonstrate that they can use the safety equipment, and follow procedures in preparing for, and during helicopter emergencies with particular focus on escaping from a helicopter following ditching\\n\\nDemonstrate sea survival and first aid techniques\\n\\nDemonstrate that they can effectively use basic firefighting equipment, and practise self-rescue techniques in low visibility situations, to include smoke filled areas.', 'target_audience' => 'The BOSIET training programme is designed for personnel new to the offshore oil and gas industry', 'prerequisites' => 'Medical Certificate', 'validity' => 4, 'category' => 'off-shore','duration' => '3', 'added_by' => '1'],
            ['code' => 'HUET','description' => 'Helicopter Underwater Escape Training', 'accreditation_body' => 'opito','aims' => 'This programme is designed for oil and gas personnel travelling to oil and gas installations/facilities via helicopter. It will prepare delegates travelling via helicopter with the specific training in pre-flight and in-flight requirements, basic emergency response knowledge and skills required in the event of an emergency - with specific focus on escaping the helicopter following ditching', 'objectives_header' => 'The objectives of the HUET Training are that delegates will be able to:', 'objectives' => 'Demonstrate, in a simulated environment, that they can use the safety equipment, and follow procedures in preparing for, and during helicopter emergencies - with particular focus on escaping from a helicopter following ditching.', 'target_audience' => 'The HUET training programme is designed for personnel travelling to oil and gas installations/facilities via helicopter.', 'prerequisites' => 'Medical Certificate', 'validity' => 4, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'FOET','description' => 'Further Offshore Emergency Training', 'accreditation_body' => 'opito','aims' => 'The FOET programme is designed to meet the further offshore safety and emergency response training requirements for personnel working in the offshore oil and gas industry. Delegates have the opportunity to practice and demonstrate emergency response skills which are not possible to practice during drills, exercises and emergency offshore training.', 'objectives_header' => 'The objectives of the FOET are that delegates will be able to:', 'objectives' => 'Demonstrate, in a simulated environment, that they can use the safety equipment and follow procedures in preparing for and during helicopter emergencies - with particular focus on escaping from a helicopter following ditching.\\n\\nDemonstrate that they can use basic firefighting equipment effectively, and use self-rescue techniques in low visibility and completely obscured visibility situations e.g. smoke filled areas.\\n\\nDemonstrate that they can perform basic first aid.', 'target_audience' => 'The FOET training programme is designed for personnel working in the offshore oil and gas industry.', 'prerequisites' => 'Medical Certificate\\n\\nValid (in-date) OPITO approved BOSIET or TBOSIET, or FOET or TFOET certificate.', 'validity' => 4, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'T-HUET','description' => 'Tropical Helicopter Underwater Escape Training', 'accreditation_body' => 'opito','aims' => 'The Tropical HUET training programme will prepare delegates that intend to travel to and from offshore oil and gas installations and vessels by helicopter in a tropical environment by providing specific training in pre-flight and in-flight requirements and to equip delegates with the basic emergency response knowledge and skills required in the event of a helicopter emergency - with specific focus on escaping from a helicopter following ditching and sea survival techniques.', 'objectives_header' => 'The objectives of the T-HUET Training are that delegates will be able to:', 'objectives' => 'Demonstrate, in a simulated environment, that they can use the safety equipment, and follow procedures in preparing for, and during helicopter emergencies - with particular focus on escaping from a helicopter following ditching\\n\\nDemonstrate sea survival techniques', 'target_audience' => 'The T-HUET programme is designed for personnel travelling to oil and gas installations/facilities via helicopter in a tropical environment.', 'prerequisites' => 'Medical Certificate', 'validity' => 4, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'T-FOET','description' => 'Tropical Further Offshore Emergency Training', 'accreditation_body' => 'opito','aims' => 'The T-FOET will provide delegates with the opportunity to practise and demonstrate emergency response skills which are not possible to practise during drills, exercises and emergency training offshore.', 'objectives_header' => 'The objectives of the T-FOET are that delegates will be able to:', 'objectives' => 'Demonstrate, in a simulated environment, that they can use the safety equipment and follow procedures in preparing for and during helicopter emergencies - with particular focus on escaping from a helicopter following ditching.\\n\\nDemonstrate that they can use basic firefighting equipment effectively, and use self-rescue techniques in low visibility and completely obscured visibility situations e.g. smoke filled areas.\\n\\nDemonstrate that they can perform basic first aid.', 'target_audience' => 'The T-FOET programme is designed for personnel working in the offshore oil and gas industry in a tropical environment.', 'prerequisites' => 'Medical Certificate\\n\\nValid (in-date) OPITO approved T-BOSIET or T-FOET or BOSIET or FOET certificate', 'validity' => 4, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'BRIDGING','description' => 'Bridging Elements Training', 'accreditation_body' => 'opito','aims' => 'The Bridging Elements Training is designed to bridge the differences between the Tropical BOSIET/FOET and the BOSIET/FOET. This includes use of aviation transit suits and emergency breathing systems (EBS) during helicopter evacuation and escape.', 'objectives_header' => null, 'objectives' => null, 'target_audience' => 'The Bridging Elements Training is designed for personnel who have undergone training in OPITO\'s Tropical BOSIET/FOET and require the extra elements to bridge the gap between the Tropical BOSIET/FOET and OPITO\'s BOSIET/FOET.', 'prerequisites' => 'Medical Certificate', 'validity' => null, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'EBS TBOSIET-THUET','description' => 'Emergency Breathing System (delivered in conjunction with T-BOSIET/T-HUET)', 'accreditation_body' => 'opito','aims' => 'The aim of the additional Emergency Breathing System (EBS) training is to complement initial offshore safety and emergency response training and assessment (i.e. T-BOSIET and T-HUET) for personnel travelling to an offshore oil and gas installation by helicopter (in a warm water tropical environment) when issued with an Emergency Breathing System (EBS).', 'objectives_header' => 'The objectives of the additional EBS training are to:', 'objectives' => 'Ensure delegates are familiar with the use of the Emergency Breathing System (EBS)\\n\\nEnsure that delegates understand the basic emergency response during a helicopter emergency using the EBS', 'target_audience' => 'The Emergency Breathing System training is designed for personnel travelling to an offshore oil and gas installation by helicopter (in a warm water tropical environment) who require additional training in the Emergency Breathing System (EBS) will complete this training delivered in conjunction with either the T-BOSIET and T-HUET course.', 'prerequisites' => 'Medical Certificate', 'validity' => 4, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'EBS TFOET','description' => 'Emergency Breathing System (delivered in conjunction with T-FOET)', 'accreditation_body' => 'opito','aims' => 'The aim of the additional Emergency Breathing System (EBS) training is to complement initial offshore safety and emergency response training and assessment (i.e. T-BOSIET or T-HUET) for personnel travelling to an offshore oil and gas installation by helicopter (in a warm water tropical environment) when issued with an Emergency Breathing System (EBS).', 'objectives_header' => 'The objectives of the additional EBS training are to:', 'objectives' => 'Ensure delegates are familiar with the use of the Emergency Breathing System (EBS)\\n\\nEnsure that delegates understand the basic emergency response during a helicopter emergency using the EBS', 'target_audience' => 'The Emergency Breathing System training is designed for personnel who wish to complete the T-FOET course and require additional training in the Emergency Breathing System (EBS) \\n\\nDelegate pre-requisites: Delegates must hold a valid (in-date) OPITO approved T-BOSIET or T-FOET or BOSIET or FOET certificate.', 'prerequisites' => 'Medical Certificate', 'validity' => 4, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'ECT-IT','description' => 'Escape Chute Training Initial Training', 'accreditation_body' => 'opito','aims' => 'The Escape Chute Initial Training programme gives delegates an understanding of how escape chutes are used as a means of tertiary escape from offshore installations and vessels and provide basic training in the use of a typical escape chute used offshore.', 'objectives_header' => null, 'objectives' => 'To make delegates aware of the various types of escape chutes used on offshore installations and vessels.\\n\\nTo provide theoretical and practical training in the safe techniques for escaping through an escape chute.\\n\\nTo ensure delegates understand what they are required to do when exiting the escape chute.', 'target_audience' => 'The Escape Chute Initial Training programme is for personnel that require offshore installation and vessel escape chute training in addition to BOSIET, FOET, T-BOSIET or T-FOET.', 'prerequisites' => 'Medical Certificate', 'validity' => 4, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'ECT REF','description' => 'Escape Chute Training Refresher Training', 'accreditation_body' => 'opito','aims' => 'The aim of the Escape Chute Refresher Training programme is to ensure delegates maintain their knowledge and skills in the use of escape chutes as a means of tertiary escape from offshore installations and vessels.', 'objectives_header' => 'To update and maintain knowledge and skills in the following:', 'objectives' => 'To make delegates aware of the various types of escape chutes used on offshore installations and vessels\\n\\nTo provide theoretical and practical training in the safe techniques for escaping through an escape chute\\n\\nTo ensure delegates understand what they are required to do when exiting the escape chute ', 'target_audience' => 'The Escape Chute Refresher Training programme is designed for personnel who are required to refresh their escape chute training and revalidate their OPITO-approved Escape Chute Training certification.', 'prerequisites' => 'Medical Certificate\\n\\nValid OPITO approved Escape Chute Training or Refresher Training certificate.', 'validity' => 4, 'category' => 'off-shore','duration' => '1', 'added_by' => '1'],
            ['code' => 'T-BOSIET','description' => 'Tropical Basic Offshore Safety Induction and Emergency Training', 'accreditation_body' => 'opito','aims' => 'The T-BOSIET will introduce delegates to the specific safety issues and regimes relevant to offshore installations, and to equip them with the basic emergency response knowledge and skills for travelling to and from offshore installations by helicopter in a tropical environment.', 'objectives_header' => 'The objectives of the T-BOSIET Training are that delegates will be able to:', 'objectives' => 'Identify the generic hazards which are specific to offshore oil and gas installations, potential risks associated with those hazards, and how controls are put in place to eliminate or reduce risks.\\n\\nIdentify key offshore related safety regulations and explain the basic safety management concepts\\n\\nDemonstrate, in a simulated environment, that they can use the safety equipment, and follow procedures in preparing for, and during helicopter emergencies - with particular focus on escaping from a helicopter following ditching\\n\\nDemonstrate sea survival and first aid techniques\\nDemonstrate that they can effectively use basic firefighting equipment, and practise self-rescue techniques in low visibility situations, to include smoke filled areas.', 'target_audience' => 'The T-BOSIET programme is designed for personnel who are new to the offshore oil and gas industry in a tropical environment.', 'prerequisites' => 'Medical Certificate', 'validity' => 4, 'category' => 'off-shore','duration' => '3', 'added_by' => '1'],
        ];

        foreach ($courses as $key => $course) {
            Course::create($course);
        }
    }
}